// Code generated by MockGen. DO NOT EDIT.
// Source: ./application/port.go
//
// Generated by this command:
//
//	mockgen -source=./application/port.go -destination=./testing/mock/application.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCSVReader is a mock of CSVReader interface.
type MockCSVReader struct {
	ctrl     *gomock.Controller
	recorder *MockCSVReaderMockRecorder
	isgomock struct{}
}

// MockCSVReaderMockRecorder is the mock recorder for MockCSVReader.
type MockCSVReaderMockRecorder struct {
	mock *MockCSVReader
}

// NewMockCSVReader creates a new mock instance.
func NewMockCSVReader(ctrl *gomock.Controller) *MockCSVReader {
	mock := &MockCSVReader{ctrl: ctrl}
	mock.recorder = &MockCSVReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCSVReader) EXPECT() *MockCSVReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockCSVReader) Read(filePath string) ([]string, [][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", filePath)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([][]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Read indicates an expected call of Read.
func (mr *MockCSVReaderMockRecorder) Read(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockCSVReader)(nil).Read), filePath)
}

// MockQueryExecutor is a mock of QueryExecutor interface.
type MockQueryExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockQueryExecutorMockRecorder
	isgomock struct{}
}

// MockQueryExecutorMockRecorder is the mock recorder for MockQueryExecutor.
type MockQueryExecutorMockRecorder struct {
	mock *MockQueryExecutor
}

// NewMockQueryExecutor creates a new mock instance.
func NewMockQueryExecutor(ctrl *gomock.Controller) *MockQueryExecutor {
	mock := &MockQueryExecutor{ctrl: ctrl}
	mock.recorder = &MockQueryExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryExecutor) EXPECT() *MockQueryExecutorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockQueryExecutor) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockQueryExecutorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockQueryExecutor)(nil).Close))
}

// CreateTable mocks base method.
func (m *MockQueryExecutor) CreateTable(tableName string, columns []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", tableName, columns)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockQueryExecutorMockRecorder) CreateTable(tableName, columns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockQueryExecutor)(nil).CreateTable), tableName, columns)
}

// InsertRows mocks base method.
func (m *MockQueryExecutor) InsertRows(tableName string, columns []string, rows [][]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRows", tableName, columns, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRows indicates an expected call of InsertRows.
func (mr *MockQueryExecutorMockRecorder) InsertRows(tableName, columns, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRows", reflect.TypeOf((*MockQueryExecutor)(nil).InsertRows), tableName, columns, rows)
}

// Query mocks base method.
func (m *MockQueryExecutor) Query(query string) ([]string, [][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", query)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([][]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Query indicates an expected call of Query.
func (mr *MockQueryExecutorMockRecorder) Query(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockQueryExecutor)(nil).Query), query)
}
